apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudnotify-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: gcr.io/PROJECT_ID/cloudnotify-worker:latest
        env:
        - name: SENDGRID_API_KEY
          valueFrom:
            secretKeyRef:
              name: sendgrid-secret
              key: api-key
        - name: TWILIO_SID
          valueFrom:
            secretKeyRef:
              name: twilio-secret
              key: sid
        - name: TWILIO_TOKEN
          valueFrom:
            secretKeyRef:
              name: twilio-secret
              key: token
        - name: TWILIO_FROM
          value: "+1234567890"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
        livenessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - "pgrep node"
          initialDelaySeconds: 10
          periodSeconds: 20
